---
- name: create folders for docker files
  file: path={{ openwrt_config_dir }}/{{ item.dir }} state=directory mode={{ item.mode }}
  with_items:
    - { dir: openwrt-1209-builder      , mode: 755 }

- name: get feeds_lines
  set_fact:
    feeds_lines: "{{ lookup('template', '../templates/openwrt-1209-builder/feeds.conf.default' ).split('\n') }}"
  when: inherit_feeds_in_dockerfile

- name: put openwrt-1209-builder Dockerfile and feeds file
  template: src=openwrt-1209-builder/{{ item }} dest={{ openwrt_config_dir }}/openwrt-1209-builder/{{ item }}
  register: builder_configs
  with_items:
    - Dockerfile
    - feeds.conf.default

- name: get numeric tags for this image if any
  shell: docker images|grep -E '^gitinsky/openwrt-1209-builder\s+[0-9,.]+\s+'|awk {'print $2'}
  failed_when: false
  changed_when: false
  register: image_tags

- name: get uuids for this image versions
  shell: docker images|grep -E '^gitinsky/openwrt-1209-builder\s+[0-9,.]+\s+'|awk {'print $3'}
  failed_when: false
  changed_when: false
  register: image_uuids
  when: image_tags.stdout_lines|length > 0

- name: build gitinsky/openwrt-1209-builder
  docker_image: path={{ openwrt_config_dir }}/openwrt-1209-builder
                name="gitinsky/openwrt-1209-builder"
                state={{ 'build' if builder_configs.changed else 'present' }}
                timeout=36000
  register: result
  until: result|success
  retries: 5
  delay: 10

- name: get image id
  shell: docker images| grep -E '^gitinsky/openwrt-1209-builder\s+latest'
  changed_when: false
  register: imagegen_image

- name: show image id
  debug: var=imagegen_image.stdout.split()[2]

- name: add version tag
  shell: "docker tag {{ imagegen_image.stdout.split()[2] }} gitinsky/openwrt-1209-builder:{{ image_tags.stdout.split('\n')| version_up }}"
  when: "image_uuids.stdout_lines is not defined or imagegen_image.stdout.split()[2] not in image_uuids.stdout_lines"
