---
- name: create folders for docker files
  file: path=/root/{{ item.dir }} state=directory mode={{ item.mode }}
  with_items:
    - { dir: openwrt-1407-builder      , mode: 755 }
    - { dir: openwrt-1407/result       , mode: 755 }

- name: put openwrt-1407-builder Dockerfile
  template: src=openwrt-1407-builder/Dockerfile dest=/root/openwrt-1407-builder/Dockerfile

- name: build gitinsky/openwrt-1407-builder
  docker_image: path=/root/openwrt-1407-builder
                name="gitinsky/openwrt-1407-builder"
                state=build
                timeout=7200
  register: result
  until: result|success
  retries: 3
  delay: 300
