---
- name: ensure done flag is removed
  file: &id001
    dest:  "/root/openwrt-{{ unirun_open_wrt_release_version }}-builder-{{ unirun_open_wrt_arch }}/logs/openwrt-{{ unirun_open_wrt_release_version }}-builder-raw.done"
    state: absent

- name: run openwrt-{{ unirun_open_wrt_release_version }}-builder and compile requested {{ unirun_open_wrt_arch }}
  docker:
    image: "gitinsky/openwrt-{{ unirun_open_wrt_release_version }}-builder"
    detach: no
    volumes:
      - "/root/openwrt-{{ unirun_open_wrt_release_version }}-builder/result:/compile/openwrt-{{ unirun_open_wrt_release_version }}/bin"
      - "/root/openwrt-{{ unirun_open_wrt_release_version }}-builder-{{ unirun_open_wrt_arch }}/logs:/compile/logs"
      - "/root/openwrt-{{ unirun_open_wrt_release_version }}-builder-{{ unirun_open_wrt_arch }}/run:/compile/run"
      - "/root/openwrt-{{ unirun_open_wrt_release_version }}-builder/config:/compile/config"
    name: "openwrt-{{ unirun_open_wrt_release_version }}-builder-{{ unirun_open_wrt_arch }}-docker-image-build"
    command: "/compile/run/universalrun.sh {{ unirun_open_wrt_config }}"
  register: docker_run

- name: show container info
  debug: var=docker_run

- name: wait for compilation completion
  wait_for:
    path: /root/openwrt-{{ unirun_open_wrt_release_version }}-builder-{{ unirun_open_wrt_arch }}/logs/openwrt-{{ unirun_open_wrt_release_version }}-builder-raw.done
    timeout: "{{ 3600*5 }}"

- name: commit image
  shell: docker commit {{ docker_run.containers[0].Id }} gitinsky/openwrt-{{ unirun_open_wrt_release_version }}-builder-{{ unirun_open_wrt_arch }}:latest

- name: remove done flag
  file: *id001

- name: remove openwrt-{{ unirun_open_wrt_release_version }}-builder-{{ unirun_open_wrt_arch }} container
  docker:
    image: gitinsky/openwrt-{{ unirun_open_wrt_release_version }}-builder
    name: "openwrt-{{ unirun_open_wrt_release_version }}-builder-{{ unirun_open_wrt_arch }}-docker-image-build"
    state: absent

- name: find out subtarget
  command: grep -E "^\s{0,}CONFIG_TARGET_[a-z,0-9]{1,}_[a-z,0-9]{1,}=y" "/root/openwrt-{{ unirun_open_wrt_release_version }}-builder/config/{{ unirun_open_wrt_config }}" |sed -E 's/CONFIG_TARGET_([^_]*)_(.*)=y/\2/'
  changed_when: false
  register: target_subtarget

- name: ensure /root/openwrt/{{ unirun_open_wrt_release_version }}/{{ unirun_open_wrt_arch }}/{{ target_subtarget.stdout }}/ esists
  file: dest="/root/openwrt/{{ unirun_open_wrt_release_version }}/{{ unirun_open_wrt_arch }}/{{ target_subtarget.stdout }}/" state=directory

- name: move files to /root/openwrt/{{ unirun_open_wrt_release_version }}/{{ unirun_open_wrt_arch }}/{{ target_subtarget.stdout }}
  command: rsync --remove-source-files --del -avc /root/openwrt-{{ unirun_open_wrt_release_version }}-builder/result/{{ unirun_open_wrt_arch }}/ /root/openwrt/{{ unirun_open_wrt_release_version }}/{{ unirun_open_wrt_arch }}/{{ target_subtarget.stdout }}/
