---
- name: include base image creation
  include: base.yml

- name: include 1407-builder image creation
  include: 1407-builder.yml

- name: include 1209-builder image creation
  include: 1209-builder.yml

#== build 1407 ar7xxx-ar9xxx
# - name: set facts for 1407 ar7xxx-ar9xxx
#   set_fact:
#     unirun_open_wrt_release_version: 1407
#     unirun_open_wrt_arch: ar7xxx-ar9xxx
#     unirun_open_wrt_config: 1407.ar71xx.config
  
- name: build 1407 ar7xxx-ar9xxx
  include: image_manager.yml unirun_open_wrt_release_version=1407 unirun_open_wrt_arch=ar7xxx-ar9xxx unirun_open_wrt_config=1407.ar71xx.config

#== build 1209 ar7xxx-ar9xxx
# - name: set facts for 1407 ar7xxx-ar9xxx
#   set_fact:
#     unirun_open_wrt_release_version: 1209
#     unirun_open_wrt_arch: ar7xxx-ar9xxx
#     unirun_open_wrt_config: 1209.ar71xx.config
#
# - name: build 1407 ar7xxx-ar9xxx
#   include: image_manager.yml
