---
- name: show variables
  debug: msg="open_wrt_release_version='{{ open_wrt_release_version }}', open_wrt_arch='{{ open_wrt_arch }}'"

- name: include base image creation
  include: base.yml

- name: include 1407-builder image creation
  include: 1407-builder.yml
  when: open_wrt_release_version == 1407

- name: include 1209-builder image creation
  include: 1209-builder.yml
  when: open_wrt_release_version == 1209

- name: build 1407 ar71xx
  include: image_manager.yml unirun_open_wrt_release_version=1407 unirun_open_wrt_arch=ar71xx
  when: open_wrt_release_version == 1407 and open_wrt_arch == 'ar71xx'

- name: build 1209 ar71xx
  include: image_manager.yml unirun_open_wrt_release_version=1209 unirun_open_wrt_arch=ar71xx
  when: open_wrt_release_version == 1209 and open_wrt_arch == 'ar71xx'

- name: build 1407 x86
  include: image_manager.yml unirun_open_wrt_release_version=1407 unirun_open_wrt_arch=x86
  when: open_wrt_release_version == 1407 and open_wrt_arch == 'x86'

- name: build 1209 x86
  include: image_manager.yml unirun_open_wrt_release_version=1209 unirun_open_wrt_arch=x86
  when: open_wrt_release_version == 1209 and open_wrt_arch == 'x86'

- name: build 1407 ramips
  include: image_manager.yml unirun_open_wrt_release_version=1407 unirun_open_wrt_arch=ramips
  when: open_wrt_release_version == 1407 and open_wrt_arch == 'ramips'

- name: build 1209 ramips
  include: image_manager.yml unirun_open_wrt_release_version=1209 unirun_open_wrt_arch=ramips
  when: open_wrt_release_version == 1209 and open_wrt_arch == 'ramips'
